### PR TITLE
Add dependencies to Linux build process

### PR DESCRIPTION
**Pull request by chrishobcroft**
Added `clang` as a pre-install requirement.

Also added `git` and `make` - just in case.

### CODE REVIEW

**Comment by chrishobcroft** [comment]
Full disclosure: this does not allow the build process to succeed, it still fails with the error per https://github.com/OrchidTechnologies/orchid/issues/31

**Comment by zaniko** [comment]
Hi
We could add rust gcc-8 g++-8 and lld too.

**Comment by criticaltv** [comment]
@zaniko - why?

**Comment by chrishobcroft** [comment]
@saurik

**Comment by zaniko** [comment]
@criticaltv because you have to install these to compile the binaries

**Comment by saurik** [comment]
@zaniko No: please do not install and use clang-8 :(. If you are going to use a system version of clang, please use at least clang-9 (which is the version we are doing all of our testing with); also, we do _not_ use lld to link: that was something someone did in one of these comment threads as it helped them bypass some argument issue... I already solved that last week for people doing local non-cross clang builds by forcing the linker to be gold.

**Comment by BorsaMetin** [comment]
👉🇹🇷👍

**Comment by saurik** [comment]
The premise of this pull request is obsolete: a while back, I replaced the poor attempt to document a distribution-specific and spiraling set of dependencies with a reference to a shell script we provide (which is actually tested as part of the CI system, and so thereby is "known to work" in a way that mere documentation can never be: if you are on Ubuntu or macOS, I expect that shell script to be almost fully comprehensive) as part of a note that indirectly mentions "the normal way this works" (which is you just run the build system and install stuff as it fails, which is the way almost everyone does C/C++). Issues like this simply lead to pull request bike shedding on something that wasn't really needed to begin with.

**Pull request closed without merging**
